### ISSUE TITLE
Seems like kraudcloud Resource Usage Donot Update When I had deleted all the apps?

### ISSUE THREAD

**Issue by HackerYunen** [kraudcloud/apps#4]
Thank you for your work!
The Resource Usage show that I had still some resource in the system, but I had deleted all the apps.
It's there are some problems about disk data not be deleted or statistics delay? 

Account: fog6682(the same github account)

**Comment by HackerYunen** [comment]
@aep Seems like no one watch this project, I need to @ you by hand.  😃

**Comment by aep** [comment]
Hi. Sorry I missed your message. We do indeed not monitor this repo.

Your disk quota includes volumes and layers. Deleting your images should free the storage quota immediately. If that doesn't work, I'll look into your account tomorrow. 

Thanks

**Comment by HackerYunen** [comment]
> 你好。对不起，我错过了你的留言。我们确实不监控这个 repo。
> 
> 您的磁盘配额包括卷和层。删除图像应该会立即释放存储配额。如果这不起作用，我明天会查看您的帐户。
> 
> 谢谢

Thanks for your reply, I found the problem base on your reply. My docker images was not deleted in the system when I just delete the app on dashboard.

But, when I want to delete the docker image, the error message show that:
```
request returned Method Not Allowed for API route and version https://docker.m.kraudcloud.com:443/v1.41/images/*******, check if the server supports the requested API version
```

Does kraudcloud do not support user to delete their own image?

**Comment by HackerYunen** [comment]
> > 你好。对不起，我错过了你的留言。我们确实不监控这个 repo。
> > 您的磁盘配额包括卷和层。删除图像应该会立即释放存储配额。如果这不起作用，我明天会查看您的帐户。
> > 谢谢
> 
> Thanks for your reply, I found the problem base on your reply. My docker images was not deleted in the system when I just delete the app on dashboard.
> 
> But, when I want to delete the docker image, the error message show that:
> 
> ```
> request returned Method Not Allowed for API route and version https://docker.m.kraudcloud.com:443/v1.41/images/*******, check if the server supports the requested API version
> ```
> 
> Does kraudcloud do not support user to delete their own image?

The cli `kra` do not support image delete too 🤣

**Comment by aep** [comment]
Try deleting by ID instead of name

**Comment by HackerYunen** [comment]
> Try deleting by ID instead of name

Success delete, thx a lot.
